kind: pipeline
type: docker
name: build-and-deploy

steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    settings:
      restore: true
      mount:
        - /root/.npm

  - name: build
    image: node:16
    environment:
      VUE_APP_API_BASE_URL:
        from_secret: VUE_APP_API_BASE_URL
      VUE_APP_BASE_URL:
        from_secret: VUE_APP_BASE_URL
    commands:
      - mkdir -p /deploy
      - npm install
      - npm run build
      - cp -r dist/* /deploy

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    commands:
      - mkdir -p /root/.npm
    settings:
      rebuild: true
      mount:
        - /root/.npm
    volumes:
      - name: deploy-volume
        path: /deploy

volumes:
  - name: deploy-volume
    host:
      path: /usr/local/cetBoot/dist